name: Run Subproject Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      # Step 3: Restore Dependencies for Test Subproject
      - name: Restore Dependencies
        run: dotnet restore ./Bank/Test/Test.csproj

      # Step 4: Build Test Subproject
      - name: Build Tests
        run: dotnet build ./Bank/Test/Test.csproj --configuration Release

      # Step 5: Run Tests
      - name: Run Tests
        run: dotnet test ./Bank/Test/Test.csproj --no-build --verbosity normal
